app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '.'
    type: 'api_platform'
    prefix: '/api' # Optional

api_login_check:
    path: /api/login_check

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
